apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-1234
  title: Testing-1234
  description: A static HTML website. Just like the good old days.
  links:
    - url: https://RoadieHQ.github.io/test-1234/
      title: Live website
  annotations:
    github.com/project-slug: RoadieHQ/test-1234
spec:
  type: website
  owner: engineering
  lifecycle: experimental
